/*
 * departements.js — Les 101 departements francais (code + nom officiel).
 *
 * Sert a reconnaitre ce que l'utilisateur tape dans le champ zone : "71",
 * "Saone-et-Loire" ou "saone et loire" designent le meme departement. La liste
 * des COMMUNES, elle, n'est pas embarquee (35 000 entrees) : elle est demandee
 * au besoin a l'API Decoupage administratif de l'Etat (geo.api.gouv.fr),
 * gratuite et sans cle, puis gardee sur l'appareil.
 *
 * Releve une fois pour toutes sur geo.api.gouv.fr/departements.
 */

export const DEPARTEMENTS = [
  { c: "01", n: "Ain" },
  { c: "02", n: "Aisne" },
  { c: "03", n: "Allier" },
  { c: "04", n: "Alpes-de-Haute-Provence" },
  { c: "05", n: "Hautes-Alpes" },
  { c: "06", n: "Alpes-Maritimes" },
  { c: "07", n: "Ardèche" },
  { c: "08", n: "Ardennes" },
  { c: "09", n: "Ariège" },
  { c: "10", n: "Aube" },
  { c: "11", n: "Aude" },
  { c: "12", n: "Aveyron" },
  { c: "13", n: "Bouches-du-Rhône" },
  { c: "14", n: "Calvados" },
  { c: "15", n: "Cantal" },
  { c: "16", n: "Charente" },
  { c: "17", n: "Charente-Maritime" },
  { c: "18", n: "Cher" },
  { c: "19", n: "Corrèze" },
  { c: "21", n: "Côte-d'Or" },
  { c: "22", n: "Côtes-d'Armor" },
  { c: "23", n: "Creuse" },
  { c: "24", n: "Dordogne" },
  { c: "25", n: "Doubs" },
  { c: "26", n: "Drôme" },
  { c: "27", n: "Eure" },
  { c: "28", n: "Eure-et-Loir" },
  { c: "29", n: "Finistère" },
  { c: "2A", n: "Corse-du-Sud" },
  { c: "2B", n: "Haute-Corse" },
  { c: "30", n: "Gard" },
  { c: "31", n: "Haute-Garonne" },
  { c: "32", n: "Gers" },
  { c: "33", n: "Gironde" },
  { c: "34", n: "Hérault" },
  { c: "35", n: "Ille-et-Vilaine" },
  { c: "36", n: "Indre" },
  { c: "37", n: "Indre-et-Loire" },
  { c: "38", n: "Isère" },
  { c: "39", n: "Jura" },
  { c: "40", n: "Landes" },
  { c: "41", n: "Loir-et-Cher" },
  { c: "42", n: "Loire" },
  { c: "43", n: "Haute-Loire" },
  { c: "44", n: "Loire-Atlantique" },
  { c: "45", n: "Loiret" },
  { c: "46", n: "Lot" },
  { c: "47", n: "Lot-et-Garonne" },
  { c: "48", n: "Lozère" },
  { c: "49", n: "Maine-et-Loire" },
  { c: "50", n: "Manche" },
  { c: "51", n: "Marne" },
  { c: "52", n: "Haute-Marne" },
  { c: "53", n: "Mayenne" },
  { c: "54", n: "Meurthe-et-Moselle" },
  { c: "55", n: "Meuse" },
  { c: "56", n: "Morbihan" },
  { c: "57", n: "Moselle" },
  { c: "58", n: "Nièvre" },
  { c: "59", n: "Nord" },
  { c: "60", n: "Oise" },
  { c: "61", n: "Orne" },
  { c: "62", n: "Pas-de-Calais" },
  { c: "63", n: "Puy-de-Dôme" },
  { c: "64", n: "Pyrénées-Atlantiques" },
  { c: "65", n: "Hautes-Pyrénées" },
  { c: "66", n: "Pyrénées-Orientales" },
  { c: "67", n: "Bas-Rhin" },
  { c: "68", n: "Haut-Rhin" },
  { c: "69", n: "Rhône" },
  { c: "70", n: "Haute-Saône" },
  { c: "71", n: "Saône-et-Loire" },
  { c: "72", n: "Sarthe" },
  { c: "73", n: "Savoie" },
  { c: "74", n: "Haute-Savoie" },
  { c: "75", n: "Paris" },
  { c: "76", n: "Seine-Maritime" },
  { c: "77", n: "Seine-et-Marne" },
  { c: "78", n: "Yvelines" },
  { c: "79", n: "Deux-Sèvres" },
  { c: "80", n: "Somme" },
  { c: "81", n: "Tarn" },
  { c: "82", n: "Tarn-et-Garonne" },
  { c: "83", n: "Var" },
  { c: "84", n: "Vaucluse" },
  { c: "85", n: "Vendée" },
  { c: "86", n: "Vienne" },
  { c: "87", n: "Haute-Vienne" },
  { c: "88", n: "Vosges" },
  { c: "89", n: "Yonne" },
  { c: "90", n: "Territoire de Belfort" },
  { c: "91", n: "Essonne" },
  { c: "92", n: "Hauts-de-Seine" },
  { c: "93", n: "Seine-Saint-Denis" },
  { c: "94", n: "Val-de-Marne" },
  { c: "95", n: "Val-d'Oise" },
  { c: "971", n: "Guadeloupe" },
  { c: "972", n: "Martinique" },
  { c: "973", n: "Guyane" },
  { c: "974", n: "La Réunion" },
  { c: "976", n: "Mayotte" },
];
